export const FETCH_INVOICES_REQUEST = "FETCH_INVOICES_REQUEST";
export const FETCH_INVOICES_SUCCESS = "FETCH_INVOICES_SUCCESS";
export const FETCH_INVOICES_FAILURE = "FETCH_INVOICES_FAILURE";
export const ADD_INVOICE = "ADD_INVOICE";
export const MARK_AS_PAID = "MARK_AS_PAID";
export const EDIT = "EDIT";
export const REMOVE = "REMOVE";

//notification types
export const ADDED_NOTIFICATION = "ADDED_NOTIFICATION";
export const DELETED_NOTIFICATION = "DELETED_NOTIFICATION";
export const DRAFT_NOTIFICATION = "DRAFT_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
