export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";
export const EDIT_USER_INFO = "EDIT_USER_INFO";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
